# Setup
title: LSB의 블로그
tagline: Tech Study Blog
url: https://leesungbin.github.io
profile_name: 이성빈
profile_bio: Univ. of Seoul / Chemical Engineering

baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true
  
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-133822239-2

# Specify the author for blog posts
author:
  name: 이성빈
  url: https://leesungbin.github.io
  email: lsb918@likelion.org

# Custom vars
version: 0.1.0
github:
  repo: https://github.com/leesungbin


# excerpt_seperator: <!--break-->